# -*- coding: utf-8 -*-
"""Untitled24.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qPeqA12PM0_jyZuwvua5nYhJsQlSNkNr
"""

import pandas as pd

data = pd.read_csv('/content/TitanicDataViz_6fd4f5e94cc1f1305048935eaca81515 (1).csv')

data.head()

data.dropna(subset=['Survived'])

numeric_cols = ['Age', 'Fare', 'SibSp', 'Parch', 'PassengerId']
for col in numeric_cols:
    data[col] = data[col].fillna(data[col].median())

data['Embarked'] = data['Embarked'].fillna(data['Embarked'].mode()[0])
data['Pclass'] = data['Pclass'].fillna(data['Pclass'].mode()[0])

cleaned_file_path = "/content/titanic_cleaned.csv"
data.to_csv(cleaned_file_path, index=False)

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

df=pd.read_csv('/content/titanic_cleaned.csv')

df.drop(['Name', 'Ticket', 'Cabin'], axis=1, inplace=True)

from sklearn.preprocessing import LabelEncoder
label_encoders = {}
for col in ['Sex', 'Embarked', 'Pclass']:
    le = LabelEncoder()
    df[col] = le.fit_transform(df[col])
    label_encoders[col] = le

df['FamilySize'] = df['SibSp'] + df['Parch'] + 1
df['IsAlone'] = (df['FamilySize'] == 1).astype(int)

df.dropna(subset=['Survived'], inplace=True)
X = df.drop('Survived', axis=1)
y = df['Survived']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

model = RandomForestClassifier(random_state=42)
model.fit(X_train, y_train)

y_pred = model.predict(X_test)
print("Accuracy:", accuracy_score(y_test, y_pred))
print("\nClassification Report:\n", classification_report(y_test, y_pred))
print("\nConfusion Matrix:\n", confusion_matrix(y_test, y_pred))

model.predict(X_test)

